language: python
python:
  - 3.3
notifications:
  email: false
install:
  - "pip install nose nose-cov --use-mirrors"
  - "python setup.py install"
script:
  - "nosetests -v --with-cover --cover-package=cloudinstall --cover-html test"
