language: python
env:
  - TOXENV=py34
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ubuntu-solutions"
    use_notice: true
    skip_join: true
install:
  - travis_retry pip install tox
script:
  - travis_retry tox