language: python
python:
  - 3.4
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ubuntu-solutions"
    use_notice: true
    skip_join: true
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "python setup.py install"
script: make ci-test
after_success:
  coveralls
