language: python
python:
  - 3.4
notifications:
  email: false
  webooks:
    - http://cypherbook.com:8080/hubot/travis
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py install"
script: make ci-test
