language: python
python:
  - 3.4
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ubuntu-solutions"
    use_notice: true
    skip_join: true
install:
  - "pip install tox"
  - "pip install coveralls"
script: tox
after_success:
  coveralls
