#cloud-config

write_files:
  - content: |
      USE_LXC_BRIDGE="true"
      LXC_BRIDGE="lxcbr0"
      LXC_ADDR="10.0.4.1"
      LXC_NETMASK="255.255.255.0"
      LXC_NETWORK="10.0.4.0/24"
      LXC_DHCP_RANGE="10.0.4.2,10.0.4.254"
      LXC_DHCP_MAX="253"
    path: /etc/default/lxc-net
  - content: |
      #!/bin/sh
      mkdir -p /dev/net || true
      mknod /dev/kvm c 10 232
      mknod /dev/net/tun c 10 200
      exit 0
    path: /etc/rc.local
    permissions: '0755'
packages:
  - libvirt-bin
  - uvtool
  - uvtool-libvirt
  - software-properties-common
  - cloud-installer
groups:
  - libvirtd: [ubuntu]
  - sudo: [ubuntu]
apt_sources:
  - source: "ppa:cloud-installer/experimental"
  - source: "ppa:juju/stable"
package_update: true
password: ubuntu
chpasswd: { expire: False }
ssh_pwauth: True

# Make sure we load our modules on first creation
runcmd:
  - [ sh, /etc/rc.local ]
  - echo "export PATH=$PATH:/usr/sbin" >> /home/ubuntu/.bashrc
