#cloud-config

write_files:
  - content: |
      auto eth0
      iface eth0 inet manual
      auto lxcbr0
      iface lxcbr0 inet dhcp
          bridge_ports eth0
    path: /etc/network/interfaces.d/bridge.cfg
  - content: |
      #!/bin/sh
      mkdir -p /dev/net || true
      mknod /dev/kvm c 10 232
      mknod /dev/net/tun c 10 200
      exit 0
    path: /etc/rc.local
    permissions: '0755'
packages:
  - libvirt-bin
  - uvtool
  - uvtool-libvirt
  - software-properties-common
  - cloud-installer
{% if extra_pkgs %}
{% for pkg in extra_pkgs %}
  - {{ pkg }}
{% endfor %}
{% endif %}
groups:
  - libvirtd: [ubuntu]
  - sudo: [ubuntu]
apt_sources:
  - source: "ppa:cloud-installer/ppa"
  - source: "ppa:juju/stable"
{% if extra_ppa %}
{% for ppa in extra_ppa %}
  - {{ ppa }}
{% endfor %}
{% endif %}
{% if extra_sshkeys %}
ssh_authorized_keys:
{% for ssh in extra_sshkeys %}
  - {{ ssh }}
{% endfor %}
{% endif %}

package_update: true
password: ubuntu
chpasswd: { expire: False }
ssh_pwauth: True

bootcmd:
  - rm /etc/network/interfaces.d/eth0.cfg
  - ifdown eth0
  - ifup lxcbr0 eth0

# Make sure we load our modules on first creation
runcmd:
  - [ sh, /etc/rc.local ]
  - echo "export PATH=$PATH:/usr/sbin" >> /home/ubuntu/.bashrc